### ISSUE TITLE
Defining Open Source Software

### ISSUE THREAD

**Issue by farisnif** [elmsln/edtechjoker#9]

**Comment by farisnif** [comment]
Open source software is a type of software that is publicly accessible and anyone has the right to inspect, edit, and run in their own environment.

**Comment by Anish-cod** [comment]
https://opensource.com/resources/what-open-source
here is a link to explore more about open source software. 
Open source refers to a type of software whose source code is available to the public, meaning anyone can view, modify, and distribute the code. This allows for collaboration and customization of the software, and encourages a community-driven development process.
